language: python
python:
- '3.7'
- '3.8'
cache:
  directories:
  - "$HOME/.wheelhouse/"
env:
  global:
  - TRAVIS_CACHE=$HOME/.travis_cache/
  matrix:
    include:
    - python: '3.7'
      env:
      - TOX_ENV=py37
    - python: '3.8'
      env:
      - TOX_ENV=py38
    - python: '3.7'
      env:
      - TOX_ENV=coverage
install:
- pip install --upgrade pip
- pip install -r test_requirements.txt
script:
- tox -e $TOX_ENV
after_success: coveralls
deploy:
  - provider: pypi
    user: "__token__"
    password:
      secure: JF24fydy8RfT1EoFZyf3Y7C0skGgYIhvd0knJHwbtyJIOli3kkNrRxtTevfo9omo8nzLLLrEj7pikbKyYfJCV3Qw9pRalZLLzQyy5SI2aEGY695mf+Se2rsnBOT9kzJEflRi4uGTILdtoXuinxS3GgFqR7iLfV7iy7TtpPMFl7HlBSK5u9uDhiE592JP6tIIfSvEvLhrKDQHBVYtdTy0xUW2Ndxy9Q2Z1Wqfz0Dzxgtihys0x0zh0rlfYLK6SutunGSPo7G3NluNu3SK9qAc4adtuirj7cQW3MKyQKTEOvZxFTlEi1Q7l7M5ciBP+BJYNNPn7gnEmioFrZtBNfKjL4kDI6usjba8mJEf6FXtjmio2uRba20zExt+ikT+pCP2yLX5+KcK9Y6rybkvnlh2CZCnfUkceIWEXPkhBjT+u61typ0kjI1GHphYjkeLzHcJLnqNAuiCn1O212VqHFXz/F/UXPw2LYl4AXJvHm754hCATg+49+JkTuvGG+W3fu2MvPL32RPXpbVDqe/sBJ+ee7vOloMGbFeUjLzvSuMU9lGFBrQSjovG5xjW3c0fBSHSqSqQiQyBukayn5F+7ducDFWTU438p2L3r0jL2QOEURW1S5DX//6ZSljNN98jC52zMWm+p3Ts2GaTjv49WaBOYOZ6nfMLJvzyZ4lzaXUsHhU=
    distributions: sdist bdist_wheel
    edge: true
    on:
      tags: true
      repo: verdan/pyatlasclient
